### PR TITLE
Add SSE bridge to MyTonWallet

### PR DESCRIPTION
**Pull request by troman29**
# Add MyTonWallet wallet

## Supports
- [x] JS bridge as a browser extention for [Google Chrome](<chrome store url>).
- [ ] JS bridge for the in-wallet browser for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] JS bridge for in-wallet browser for [Windows](<link>), [macOS](<link>), ... .
- [ ] HTTP bridge as a mobile wallet app for [iOS](<appstore link>) and [Android](<google play link>).
- [x] HTTP bridge as a desktop wallet app for [Windows](<link>), [macOS](<link>), [Linux](<link>).

## Supported features
- [x] [ton_proof](https://github.com/ton-connect/docs/blob/main/requests-responses.md#address-proof-signature-ton_proof)
- [x] [SendTransaction](https://github.com/ton-connect/docs/blob/main/requests-responses.md#methods)

## Tests
- https://static.obbana.ru/demo-dapp-with-react-ui/index.html
  - Unfortunately, the `sendTransaction` button performs unnecessary redirection (not our problem), otherwise it works

### Builds
- Windows https://disk.yandex.ru/d/-ARMLrGXT2dFmA
- Linux https://disk.yandex.ru/d/1Rp9lPxNwGw-dA
- MacOS (on demand)

## Integrator contacts
* telegram
  * https://t.me/troman29
  * https://t.me/unexpectedusername

### CODE REVIEW

**Comment by troman29** [comment]
PR is ready, I have added builds

**Comment by LetikGit** [comment]
When called sendTransaction, no parameters are passed in UI

```
{
"address":"0:412410771DA82CBA306A55FA9E0D43C9D245E38133CB58F1457DFB8D5CD8892F"
"amount":"20000000"
}
```
3G2rmgsT5D


You mean it problem?

> Unfortunately, the sendTransaction button performs unnecessary redirection (not our problem), otherwise it works

**Comment by troman29** [comment]
> This error reproducing if connect wallet and call send Transaction without refresh page. If refresh page after login - the error is gone and a modal window with translations has started to be displayed.

Okay, I'll figure it out today

**Comment by troman29** [comment]
> This error reproducing if connect wallet and call send Transaction without refresh page. If refresh page after login - the error is gone and a modal window with translations has started to be displayed.

@LetikGit I can't reproduce, I think the problem is in an unstable  toncenter.com API (`LITE_SERVER_UNKNOWN`, `LITE_SERVER_NOTREADY`) , I updated the builds, it became more stable.

**Pull request merged**
