### PR TITLE
Add SafePal Wallet

### PR DESCRIPTION
**Pull request by SafePalWallet**
Add SafePal wallet info

# Add <WALLET_NAME> wallet

## Supports
- [x] JS bridge as a browser extention for [Google Chrome](<chrome store url>), ..., browsers.
- [x] JS bridge for the in-wallet browser for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] JS bridge for in-wallet browser for [Windows](<link>), [macOS](<link>), ... .
- [x] HTTP bridge as a mobile wallet app for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] HTTP bridge as a desctop wallet app for [Windows](<link>), [macOS](<link>), ... .

## Supported features
- [x] [ton_proof](https://github.com/ton-connect/docs/blob/main/requests-responses.md#address-proof-signature-ton_proof)
- [x] [SendTransaction](https://github.com/ton-connect/docs/blob/main/requests-responses.md#methods)

## Tests
[a demo dapp with integrated wallet](link)

## Integrator contacts
* telegram
* email
* discord
* ...

### CODE REVIEW

**Comment by SafePalWallet** [comment]
Please test with SafePal Wallet App V4.7.1

**Comment by LetikGit** [comment]
> Please test with SafePal Wallet App V4.7.1

The last available version is 4.7.0

**Comment by SafePalWallet** [comment]
> > Please test with SafePal Wallet App V4.7.1
> 
> The last available version is 4.7.0

Now the last available version is 4.7.1, please test, thanks

**Comment by LetikGit** [comment]
> > > Please test with SafePal Wallet App V4.7.1
> > 
> > 
> > The last available version is 4.7.0
> 
> Now the last available version is 4.7.1, please test, thanks

The problem still exists. You can check it on dns.ton.org or on sandbox (https://ton-connect.github.io/demo-dapp-with-react-ui/) using the last version for Android (4.7.1)
I tested with the app installed from the APK file, not from Google Play, if it is important.

**Comment by SafePalWallet** [comment]
> > > > Please test with SafePal Wallet App V4.7.1
> > > 
> > > 
> > > The last available version is 4.7.0
> > 
> > 
> > Now the last available version is 4.7.1, please test, thanks
> 
> The problem still exists. You can check it on dns.ton.org or on sandbox (https://ton-connect.github.io/demo-dapp-with-react-ui/) using the last version for Android (4.7.1) I tested with the app installed from the APK file, not from Google Play, if it is important.

Can you tell me the details of the problem?

**Comment by LetikGit** [comment]
> I have added deepLink field, "deepLink": "safepal-tc://", the dapp https://ton-connect.github.io/demo-dapp-with-react-ui is updated walletlist-v2.json? Can you tell me the details of the problem?

It works well with iOS, but with Android exist some problem. 

Step-by-step
1. I click "Connect wallet"
2. Choose "SafePal" from the list
3. It redirects me to link.safepal.io with some GET-params
4. Then it redirects me to safepal.com/download also with some GET-params and shows me links for SafePal App on different platforms

Screencast:

https://github.com/ton-blockchain/wallets-list/assets/48149254/d56045fe-8cef-49c6-9c27-e62e5e407768

**Comment by SafePalWallet** [comment]
> > I have added deepLink field, "deepLink": "safepal-tc://", the dapp https://ton-connect.github.io/demo-dapp-with-react-ui is updated walletlist-v2.json? Can you tell me the details of the problem?
> 
> It works well with iOS, but with Android exist some problem.
> 
> Step-by-step
> 
> 1. I click "Connect wallet"
> 2. Choose "SafePal" from the list
> 3. It redirects me to link.safepal.io with some GET-params
> 4. Then it redirects me to safepal.com/download also with some GET-params and shows me links for SafePal App on different platforms
> 
> Screencast:
> 
>  rec-safepal.mp4

I have removed universal_url, then Android and iOS would use deepLink?

**Comment by crazyministr** [comment]
@tolya-yanot the json file is broken
comma is missing here https://github.com/ton-blockchain/wallets-list/pull/56/files#diff-8004369fa8aef55feb4201369a235b56858bd61d6a2af2fe57eed77397ec10b9R158

**Pull request merged**
