### PR TITLE
Add DeWallet wallet

### PR DESCRIPTION
**Pull request by deivana**
# Add DeWallet wallet

## Supports
- [x] JS bridge as a browser extention for [Google Chrome](<chrome store url>), ..., browsers.
- [ ] JS bridge for the in-wallet browser for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] JS bridge for in-wallet browser for [Windows](<link>), [macOS](<link>), ... .
- [ ] HTTP bridge as a mobile wallet app for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] HTTP bridge as a desctop wallet app for [Windows](<link>), [macOS](<link>), ... .

## Supported features
- [x] [ton_proof](https://github.com/ton-connect/docs/blob/main/requests-responses.md#address-proof-signature-ton_proof)
- [x] [SendTransaction](https://github.com/ton-connect/docs/blob/main/requests-responses.md#methods)

## Tests
https://ton-connect.github.io/demo-dapp-with-react-ui/

https://user-images.githubusercontent.com/116902337/229241661-e3ac7cbd-3c8a-436d-b625-3b890b5b88d4.mp4

https://user-images.githubusercontent.com/116902337/231009436-a97042e3-ef6f-448c-b264-5da71d2affce.mp4

## Integrator contacts
* telegram @ivan_bridge

### CODE REVIEW

**Comment by deivana** [comment]
Install link: https://chrome.google.com/webstore/detail/dewallet/pnccjgokhbnggghddhahcnaopgeipafg

**Comment by deivana** [comment]
when to expect an answer?

**Comment by LetikGit** [comment]
There are some problems with connecting the wallet with TonConnect in the Sandbox

https://ton-connect.github.io/demo-dapp-with-react-ui/

chrome_JNSIKI3ypw

**Comment by deivana** [comment]
[Архив.zip](https://github.com/ton-blockchain/wallets-list/files/11194354/default.zip)

All bugs are fixed, install the beta version locally and check. Updates in the store will be released in 2-3 days.

**Comment by deivana** [comment]
Extension published, please update to version 1.4 and check.

**Comment by deivana** [comment]
> There are some problems with connecting the wallet with TonConnect in the Sandbox
> 
> https://ton-connect.github.io/demo-dapp-with-react-ui/
> 
> chrome_JNSIKI3ypw [ chrome_JNSIKI3ypw ](https://user-images.githubusercontent.com/48149254/230955597-3e771fd2-414e-4687-985d-5b3b3fdd2933.gif) [ ](https://user-images.githubusercontent.com/48149254/230955597-3e771fd2-414e-4687-985d-5b3b3fdd2933.gif)
Extension published, please update to version 1.4 and check.

**Comment by LetikGit** [comment]
Still problems with connection in the sandbox.
screen


400 error 
`message
: 
"proof checking error: not enough bytes for magic prefix"`

**Comment by deivana** [comment]
I do not see this bug, please check on another device or provide more detailed information about the bug.

**Comment by deivana** [comment]
Your wallet is not initialized - so it is not possible to carry out ton_proof. Initialize the wallet and check again.

**Comment by deivana** [comment]
This bug fixed. Updates in the store will be released in 1-2 days.

**Comment by deivana** [comment]
Fix in version 1.5

**Comment by mounteblood** [comment]
@LetikGit New version is available.
Update the extension to 1.5 and check.

**Comment by tolya-yanot** [comment]
merged to master

**Pull request closed without merging**
