### PR TITLE
feat: update gatewallet

### PR DESCRIPTION
**Pull request by weixuefeng**
# Add Gate wallet

## Supports
- [x] JS bridge for the in-wallet browser for [iOS](https://www.gate.io/zh/mobileapp) and [Android](https://www.gate.io/zh/mobileapp).
- [x] HTTP bridge as a mobile wallet app for [iOS](https://www.gate.io/zh/mobileapp) and [Android](https://www.gate.io/zh/mobileapp).

## Supported features
- [x] [ton_proof](https://github.com/ton-connect/docs/blob/main/requests-responses.md#address-proof-signature-ton_proof)
- [x] [SendTransaction](https://github.com/ton-connect/docs/blob/main/requests-responses.md#methods)

## Tests
[a demo dapp with integrated wallet](https://weixuefeng.github.io/demo-dapp-with-wallet/)

### CODE REVIEW

**Review by thekiba — APPROVED** [review]

**Comment by weixuefeng** [comment]
> Forbidden when connect

which version?

**Comment by itsminh99** [comment]
I'm using latest version. When I click to gate wallet then open 1 url https://gateio.onelink.me/DmA6/web3?v=2&id=47cc8ece7ed4c6676aff363a17000875ec9664ce9c1d6cae472ed86df953882f&r=%7B%2522manifestUrl%2522%253A%2522https%253A%252F%252F192.168.1.59%253A5173%252Ftonconnect-manifest.json%2522,%2522items%2522%253A%5B%7B%2522name%2522%253A%2522ton_addr%2522%7D%5D%7D&ret=tg%253A%252F%252Fresolve (Forbidden) and scan QR by Gate.io app then black screen

**Comment by weixuefeng** [comment]
> I'm using latest version. When I click to gate wallet then open 1 url https://gateio.onelink.me/DmA6/web3?v=2&id=47cc8ece7ed4c6676aff363a17000875ec9664ce9c1d6cae472ed86df953882f&r=%7B%2522manifestUrl%2522%253A%2522https%253A%252F%252F192.168.1.59%253A5173%252Ftonconnect-manifest.json%2522,%2522items%2522%253A%5B%7B%2522name%2522%253A%2522ton_addr%2522%7D%5D%7D&ret=tg%253A%252F%252Fresolve (Forbidden) and scan QR by Gate.io app then black screen

i had make pull request https://github.com/ton-blockchain/wallets-list/pull/122

**Comment by itsminh99** [comment]
Is it works? It open a link and can't click any buttons
IMG_B0A1E1DFB167-1

**Pull request merged**
