### PR TITLE
SafePal TonConnect 2.0

### PR DESCRIPTION
**Pull request by bryanRRRR**
# Add <SafePal> wallet

## Supports
- [x] JS bridge as a browser extention for [Google Chrome](<chrome store url>), ..., browsers.
- [x] JS bridge for the in-wallet browser for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] JS bridge for in-wallet browser for [Windows](<link>), [macOS](<link>), ... .
- [ ] HTTP bridge as a mobile wallet app for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] HTTP bridge as a desctop wallet app for [Windows](<link>), [macOS](<link>), ... .

## Supported features
- [x] [ton_proof](https://github.com/ton-connect/docs/blob/main/requests-responses.md#address-proof-signature-ton_proof)
- [x] [SendTransaction](https://github.com/ton-connect/docs/blob/main/requests-responses.md#methods)

## Tests
Android: https://www.safepal.com/en/download 
extention: https://chromewebstore.google.com/detail/safepal-extension-wallet/lgmpcpglpngdoalbgeoldeajfclnhafa

Dapp: https://ton-connect.github.io/demo-dapp-with-react-ui/   
Dapp: https://getgems.io/

## Integrator contacts
*@bryan2021
* lxs417143914@gmail.com
* discord
* ...

### CODE REVIEW

**Comment by siandreev** [comment]
Hi @bryanRRRR ! Could you please edit this PR and add missing information?
image

**Comment by ceoooooo** [comment]
@bryanRRRR Brother it's been a year !!! ???? What are the chances that safe pal will be able to finish the PR

**Comment by ceoooooo** [comment]
@bryanForSafe What is the likelihood of integration with the blockchain TON?

**Review by bryanRRRR — COMMENTED** [review]
Update code

**Comment by bryanRRRR** [comment]
Sorry it's too late to answer you.
I have updated my wallet to a new version now, is this correct?

**Comment by bryanRRRR** [comment]
Sorry it's too late to answer you.
I have updated my wallet to a new version now, is this correct?

**Pull request closed without merging**
